#! /bin/bash

BLUE="\033[0;34m"
ORANGE="\033[0;33m"
LIGHTBLUE="\033[1;34m"
GREEN="\033[0;32m"
RED="\033[0;31m"
PURPLE="\033[0;35m"
RESET="\033[0m"

#executes script which checks the hashed input against the password hash in the
# secret.txt pre-generated by the script
./scripts/passwordCheck.sh

#passwordCheck.sh will exit with 0 if user enters correct password.
#if exit value == 0, the options below will appear
while [ "$?" -eq "0" ]; do
	echo
	echo -e ${LIGHTBLUE}1. Create a folder${RESET}
	echo -e ${ORANGE}2. Copy a folder${RESET}
	echo -e ${LIGHTBLUE}3. Set a password${RESET}
	echo -e ${ORANGE}4. Calculator${RESET}
	echo -e ${LIGHTBLUE}5. Create week folders${RESET}
	echo -e ${ORANGE}6. Check filenames${RESET}
	echo -e ${LIGHTBLUE}7. Download a file${RESET}
	echo -e ${ORANGE}8. Exit${RESET}
	echo

	read -p "$(echo -e ${GREEN}Please choose an option: ${RESET})" option
	echo

	#takes input and uses a case statement  to determine the action
	case $option in
	
		"1")
		./scripts/folderMaker.sh;; #runs folderMaker script

		"2")
		./scripts/folderCopier.sh;; #runs folderCopier script

		"3")
		./scripts/setPassword.sh;; #runs setPassword script

		"4")
                ./scripts/calculator.sh;; #runs calculator script

		"5")
		read -p "$(echo -e ${GREEN}Enter number for start folder: ${RESET})" ARG1
		read -p "$(echo -e ${GREEN}Enter number for end folder: ${RESET})" ARG2
                ./scripts/megaFolderMaker.sh "$ARG1" "$ARG2";; #runs megaFolderMaker script
		
		"6")
                ./scripts/filenames.sh;; #runs filenames script

		"7")
                ./scripts/webDownloader.sh;; #runs webDownloader script

		"8")
		break;;

		*)
		echo "Invalid choice" #wildcard catches any other input and returns error message
	esac
done
