#! /bin/bash

#executes script which checks the hashed input against the password hash in the
# secret.txt pre-generated by the script
./passwordCheck.sh

#passwordCheck.sh will exit with 0 if user enters correct password.
#if exit value == 0, the options below will appear
if [ "$?" -eq "0" ]; then
echo  "1. Create a folder
2. Copy a folder
3. Set a password"
fi

read -p "Please choose an option: " option
#takes input and uses a case statement  to determine the action
case $option in
	
	"1")
	./folderMaker.sh;; #runs folderMaker script

	"2")
	./folderCopier.sh;; #runs folderCopier script

	"3")
	./setPassword.sh;; #runs setPassword script
	
	*)
	echo "Invalid choice" #wildcard catches any other input and returns error message
esac
